export default {
  background: "#fafafa",
  primary: "#bb86fc",
  secondary: "#03dac6",
  onBackground: "#ffffff",
  onPrimary: `#000000`,
  onSecondary: `#000000`,
  surface: "#1b191f",
  formBorder: "black",
  navbarColor: "#1b191f",
  onNavbar: `white`,
  tag: "#bb86fc",
  inlineTag: "#bb86fc",
  onInlineTag: "lighten(rgba(0, 0, 0, 0.87), 1%)",
  selectedTag: "#8f9bff",
  calloutBorder: "#bb86fc",
}
